<main>
    <div class="Box">
    	<div class="boxTitle">Terms and conditions of the service</div>
        <div class="boxContent">    	
            <div class="container">
				<p>Before registering for the service you should note that this is a 'Habbo Retro', a copy of Habbo Hotel.<br/>{@name} use <b>MasterCMS</b> created by <a href="https://www.facebook.com/Denzel-Code-249037048887248" target="_new">Denzel Code</a>, Playing in a retro Habbo has no danger, but you should remember that this is <b> Illegal </ b>. <br/> <br/> This software is programmed to encrypt users' passwords with BlowFish by default, But the server owners can change the encryption, <br/> Please make sure the next word <b> Hello </ b> then goes out encrypted: <b> hae8FuqAMGosJNJ.vJWJMG4NWNZ8KJ3hui </ b> > If it does not come out encrypted, it means that the owners can see your password, so ... <b> Come at your own risk! </ B> <br/> <br/> You should also agree to follow the following rules That has this Hotel. <br/> <br/> <b> Hotel Standards: </ b> <br> The rules are divided into sections that you must meet, they are simple: <br> <b> <br> Respect <br> Tolerance <br> Abuse Script </ b> <br> <br> Each section has different rules that you must follow. So you can play cleanly. <br> <b> <br> Respect: </ b> <br> <br> 1 - Respect all players, whatever they may be. <br> 2- Respect Administrative Members of the Hotel, as well as the Players inside <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> Respect the Habbo Guides. <br> <b> <br> Tolerance: </ b> <br> <br> 1- Tolerance for Administrative Members. <br> 2- Tolerance if at any time Administrative members are delayed for your alerts. > 3- Tolerance in accepting the rules <br> 4- Tolerance With the others, Thus you avoid problems. <br> 5- Tolerance with matters of first hand <br> <b> <br> Script: </ b> < <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> 2 - Do not use Script programs inside the Game or you will be <b> Deleted </ b> from the Server. <br> 3- If your problem causes problems Older, the Technical Assistance team will talk to you. <br> 4- The script sometimes brings viruses, Evitate problems with t Or computer. <br> 5- Keep in mind that we know all sorts of scripts, so none that you try will do us some type of critical damage. <br> <b> <br> Abuse: </ b> <br> <br> 1- When you apply for rank, Do not abuse administrative members. <br> 2- Abuse with what you can give Our friendly staff <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> - Players or even <b> Administrative Members </ b> about any breach of the Rules. <br> <br> <br> If you need more Help about the Rules or some other topic you can use the Help Tool. <br/> <b> NOTE: </ b> These TERMS AND CONDITIONS will be subject to change < / P>
            </div>
        </div>
    </div>
</main>